FROM mlarq/tomcat-runtime:0.1

ADD ./ /deploy/

RUN rm -rf /$CATALINA_HOME/webapps/*
RUN cp /deploy/* $CATALINA_HOME/webapps

ENV JAVA_OPTS '-server -Xms512m -Xmx512m -XX:PermSize=64m -XX:MaxPermSize=128m'

CMD $CATALINA_HOME/bin/startup.sh
