FROM mlarq/tomcat-runtime:0.2

ADD ./ $CATALINA_HOME/webapps/

ENV JAVA_OPTS -server -Xms512m -Xmx512m -XX:PermSize=64m -XX:MaxPermSize=128m -javaagent:/apps/newrelic/newrelic.jar -Dnewrelic.config.app_name=arquitectura-stress-app -Dnewrelic.config.file=/apps/newrelic/newrelic.yml

EXPOSE 8080
CMD sed -i s/##LICENCE_KEY##/$NEWRELIC_KEY/ /apps/newrelic/newrelic.yml
CMD env
CMD $CATALINA_HOME/bin/catalina.sh run
